DROP TABLE IF EXISTS player_games;

CREATE TABLE player_games (
    PLAYER_ID INTEGER,
    PLAYER_NAME TEXT,
    GAME_DATE TEXT,
    GAME_ID TEXT,
    TEAM_ABBREVIATION TEXT,
    MATCHUP TEXT,
    MIN INTEGER,
    FG3M INTEGER,
    FG3A INTEGER
);
